update

diff --git a/hackerrank/heap/gen b/hackerrank/heap/gen
--- a/hackerrank/heap/gen
+++ b/hackerrank/heap/gen
@@ -1,56 +1,41 @@
-import java.io.*;
-import java.util.Arrays;
+#!/usr/bin/env bash
 
-public class AliceBob {
+if [ -z "$1" ]
+  then
+    echo "Error : No file name supplied"
+    exit 1
+fi
+
+FILE_NAME="$1.java"
+INPUT_FILE="$1_INPUT.txt"
+CLASS_NAME="$1"
+
+if [ -e "$FILE_NAME" ]
+then
+    echo "Error : File Already Exist"
+else
+    echo "import java.io.*;
+
+public class $CLASS_NAME {
     BufferedReader bf;
     PrintWriter writer;
     StringBuilder sb;
     static boolean local_system = true;
 
-    long mod = 1_000_000_007L;
-
-    long pow(long a,long b){
-        long p = 1L;
-        for(;b>0;a=a*a%mod,b>>=1)
-            if((b&1) == 1) p=p*a%mod;
-        return p;
-    }
-
-    long[][] fif(int n){
-        long[][] fif = new long[2][n+1];
-        fif[1][0] = fif[0][0] = 1;
-        for(int i = 1,h=fif[0].length;i<h;i++){
-            fif[0][i] = i * fif[0][i-1] % mod;
-            fif[1][i] = pow(fif[0][i],mod - 2);
-        }
-        return fif;
-    }
-
     void run() throws IOException {
-        int t = i();
-        long[][] fif = fif(1000000<<1);
-        while(t-->0){
-            int[] c = ni();
-            int times = c[0] - c[1] + 1;
-            int start= c[2] - 1;
-            long sum = 0L;
-            for(int i = 0;i<times;i++){
-                sum = (sum + ((fif[0][start + i] * ((fif[1][start] * fif[1][i])%mod))%mod))%mod;;
-            }
-            writer.println(sum);
-        }
+      
     }
 
     public static void main(String[] args) throws IOException {
         long start_time = System.currentTimeMillis();
-        AliceBob obj = new AliceBob();
+        $CLASS_NAME obj = new $CLASS_NAME();
         obj.run();
         long end_time = System.currentTimeMillis();
-        if (local_system) obj.writer.println("Time : " + (end_time - start_time));
+        if (local_system) obj.writer.println(\"Time : \" + (end_time - start_time));
         obj.close();
     }
 
-    public AliceBob(){
+    public $CLASS_NAME(){
         writer = new PrintWriter(System.out);
         bf = new BufferedReader(new InputStreamReader(System.in));
         sb = new StringBuilder();
@@ -65,14 +50,14 @@ public class AliceBob {
     }
 
     public int[] ni() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         int[] send = new int[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Integer.parseInt(data[i]);
         return send;
     }
 
     public long[] nl() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         long[] send = new long[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Long.parseLong(data[i]);
         return send;
@@ -84,3 +69,8 @@ public class AliceBob {
         bf.close();
     }
 }
+
+" > "$FILE_NAME"
+
+echo "" > "$INPUT_FILE"
+fi
