update

diff --git a/cses/gen b/cses/gen
--- a/cses/gen
+++ b/cses/gen
@@ -1,54 +1,41 @@
-import java.io.*;
+#!/usr/bin/env bash
 
-public class _1392B {
+if [ -z "$1" ]
+  then
+    echo "Error : No file name supplied"
+    exit 1
+fi
+
+FILE_NAME="$1.java"
+INPUT_FILE="$1_INPUT.txt"
+CLASS_NAME="$1"
+
+if [ -e "$FILE_NAME" ]
+then
+    echo "Error : File Already Exist"
+else
+    echo "import java.io.*;
+
+public class $CLASS_NAME {
     BufferedReader bf;
     PrintWriter writer;
     StringBuilder sb;
-    static boolean local_system = false;
-
-    /*
-        1 2 3 4 5
-        4 3 2 1 0
-        0 1 2 3 4
-    */
+    static boolean local_system = true;
 
     void run() throws IOException {
-        int t = i();
-        while(t-->0){
-            
-            long[] c = nl();
-            int[] d = ni();
-            int min = d[0];
-            int max = d[0];
-            for(int e : d){
-                max = Math.max(e,max);
-                min = Math.min(e,min);
-            }
-            if((c[1]&1)==1)
-                for(int i = 0,h=d.length;i<h;i++)
-                    d[i] = max - d[i];
-            else
-                for(int i = 0,h=d.length;i<h;i++)
-                    d[i] = d[i] - min;
-                
-        
-            for(int e : d)
-                sb.append(e).append(" ");
-            sb.append("\n");
-        }
-        writer.println(sb.toString().trim());
+      
     }
 
     public static void main(String[] args) throws IOException {
         long start_time = System.currentTimeMillis();
-        _1392B obj = new _1392B();
+        $CLASS_NAME obj = new $CLASS_NAME();
         obj.run();
         long end_time = System.currentTimeMillis();
-        if (local_system) obj.writer.println("Time : " + (end_time - start_time));
+        if (local_system) obj.writer.println(\"Time : \" + (end_time - start_time));
         obj.close();
     }
 
-    public _1392B(){
+    public $CLASS_NAME(){
         writer = new PrintWriter(System.out);
         bf = new BufferedReader(new InputStreamReader(System.in));
         sb = new StringBuilder();
@@ -63,14 +50,14 @@ public class _1392B {
     }
 
     public int[] ni() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         int[] send = new int[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Integer.parseInt(data[i]);
         return send;
     }
 
     public long[] nl() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         long[] send = new long[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Long.parseLong(data[i]);
         return send;
@@ -82,3 +69,8 @@ public class _1392B {
         bf.close();
     }
 }
+
+" > "$FILE_NAME"
+
+echo "" > "$INPUT_FILE"
+fi
