update

diff --git a/codechef/LTIME91A/gen b/codechef/LTIME91A/gen
--- a/codechef/LTIME91A/gen
+++ b/codechef/LTIME91A/gen
@@ -1,40 +1,41 @@
-import java.io.*;
+#!/usr/bin/env bash
 
-public class MaximumSubarraySum {
+if [ -z "$1" ]
+  then
+    echo "Error : No file name supplied"
+    exit 1
+fi
+
+FILE_NAME="$1.java"
+INPUT_FILE="$1_INPUT.txt"
+CLASS_NAME="$1"
+
+if [ -e "$FILE_NAME" ]
+then
+    echo "Error : File Already Exist"
+else
+    echo "import java.io.*;
+
+class $CLASS_NAME {
     BufferedReader bf;
     PrintWriter writer;
     StringBuilder sb;
-    static boolean local_system = false;
+    static boolean local_system = true;
 
     void run() throws IOException {
-        i();
-        int[] d = ni();
-        long p = 0;
-        long m = 0;
-        long s = Integer.MIN_VALUE;
-        for(int e : d){
-            p+=e;
-            s = Math.max(p-m,s);
-            m = Math.min(p,m);
-        }
-        writer.println(s);
-    }
-
-    public static int sm(int[] d){
-        
-        return 0;
+      
     }
 
     public static void main(String[] args) throws IOException {
         long start_time = System.currentTimeMillis();
-        MaximumSubarraySum obj = new MaximumSubarraySum();
+        $CLASS_NAME obj = new $CLASS_NAME();
         obj.run();
         long end_time = System.currentTimeMillis();
-        if (local_system) obj.writer.println("Time : " + (end_time - start_time));
+        if (local_system) obj.writer.println(\"Time : \" + (end_time - start_time));
         obj.close();
     }
 
-    public MaximumSubarraySum(){
+    public $CLASS_NAME(){
         writer = new PrintWriter(System.out);
         bf = new BufferedReader(new InputStreamReader(System.in));
         sb = new StringBuilder();
@@ -49,24 +50,27 @@ public class MaximumSubarraySum {
     }
 
     public int[] ni() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         int[] send = new int[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Integer.parseInt(data[i]);
         return send;
     }
 
     public long[] nl() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         long[] send = new long[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Long.parseLong(data[i]);
         return send;
     }
 
-    public void close() throws IOException{
+    public void close() throws IOException {
         writer.flush();
         writer.close();
         bf.close();
     }
 }
 
+" > "$FILE_NAME"
 
+echo "" > "$INPUT_FILE"
+fi
