update

diff --git a/cses/dataStarCoaching/gen b/cses/dataStarCoaching/gen
--- a/cses/dataStarCoaching/gen
+++ b/cses/dataStarCoaching/gen
@@ -1,47 +1,41 @@
-import java.io.*;
-import java.util.Map;
-import java.util.TreeMap;
-import java.util.Map.Entry;
+#!/usr/bin/env bash
 
-public class Towers {
+if [ -z "$1" ]
+  then
+    echo "Error : No file name supplied"
+    exit 1
+fi
+
+FILE_NAME="$1.java"
+INPUT_FILE="$1_INPUT.txt"
+CLASS_NAME="$1"
+
+if [ -e "$FILE_NAME" ]
+then
+    echo "Error : File Already Exist"
+else
+    echo "import java.io.*;
+
+public class $CLASS_NAME {
     BufferedReader bf;
     PrintWriter writer;
     StringBuilder sb;
-    static boolean local_system = false;
+    static boolean local_system = true;
 
     void run() throws IOException {
-        int n = i();
-        int[] d = ni();
-        TreeMap<Integer,Integer> hash = new TreeMap<>();
-        for(int i = 0;i<n;i++){
-            Entry<Integer,Integer> entry = hash.higherEntry(d[i]);
-            if(entry == null){
-                hash.put(d[i], hash.getOrDefault(d[i],0)+1);
-            }else{
-                int key = entry.getKey();
-                int new_key = d[i];
-                if(entry.getValue() == 1) hash.remove(key);
-                else hash.put(key, entry.getValue() - 1);
-                hash.put(new_key, hash.getOrDefault(new_key, 0) + 1);
-            }
-        }
-        long count = 0;
-        for(Entry<Integer,Integer> entry  : hash.entrySet()){
-            count += entry.getValue();
-        }
-        writer.println(count);
+      
     }
 
     public static void main(String[] args) throws IOException {
         long start_time = System.currentTimeMillis();
-        Towers obj = new Towers();
+        $CLASS_NAME obj = new $CLASS_NAME();
         obj.run();
         long end_time = System.currentTimeMillis();
-        if (local_system) obj.writer.println("Time : " + (end_time - start_time));
+        if (local_system) obj.writer.println(\"Time : \" + (end_time - start_time));
         obj.close();
     }
 
-    public Towers(){
+    public $CLASS_NAME(){
         writer = new PrintWriter(System.out);
         bf = new BufferedReader(new InputStreamReader(System.in));
         sb = new StringBuilder();
@@ -56,14 +50,14 @@ public class Towers {
     }
 
     public int[] ni() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         int[] send = new int[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Integer.parseInt(data[i]);
         return send;
     }
 
     public long[] nl() throws IOException {
-        String[] data = bf.readLine().split(" ");
+        String[] data = bf.readLine().split(\" \");
         long[] send = new long[data.length];
         for (int i = 0, h = data.length; i < h; i++) send[i] = Long.parseLong(data[i]);
         return send;
@@ -76,4 +70,7 @@ public class Towers {
     }
 }
 
+" > "$FILE_NAME"
 
+echo "" > "$INPUT_FILE"
+fi
